#!/usr/bin/python3
"""scripts/docs/gen_reference.py [ROOT]

Writes the generated reference pages under docs/reference/ from the code itself, so they cannot fall behind it:
  docs/reference/tools/<tool>.md   one page per program in bin/: its own docstring (or header comment), the lessons
                                   it cites, the ledger events it writes, a link to its source
  docs/reference/tools/README.md   the index of those pages
  docs/reference/ledger-events.md  every ledger event type, and which tools write it
  docs/reference/hook-refusals.md  every refusal the hook can give, grouped by the function that gives it
Never edit a generated page: change the docstring or the code and run this again. scripts/docs/check_docs.py (and the
suites, through tests/test_tools.py) refuse a generated page that differs from what this would write now.
ROOT defaults to the kit this file is in. Stdlib only.
"""
import ast
import os
import re
import sys

GEN_MARK = "<!-- Generated by scripts/docs/gen_reference.py from the code. Do not edit: change the source and regenerate. -->"
LESSON_CITE = re.compile(r'LESSONS\.md ["“]([^"”]+)["”]')
EVENT_NAME = re.compile(r"^[A-Z][A-Z0-9]*(?:-[A-Z0-9]+)*$")
EVENT_SH = re.compile(r'bin/ledger"?\s+(?:-r\s+"[^"]*"\s+|-r\s+\S+\s+)?([A-Z][A-Z0-9]*(?:-[A-Z0-9]+)*)\b')
HOOK = os.path.join(".claude", "hooks", "sandbox.py")


def is_python(path):
    if path.endswith(".py"):
        return True
    with open(path, errors="replace") as f:
        return "python" in f.readline()


def own_doc(path):
    """The tool's docstring, or for a shell script its comment block after the shebang."""
    src = open(path, errors="replace").read()
    if is_python(path):
        try:
            return (ast.get_docstring(ast.parse(src)) or "").strip()
        except SyntaxError:
            return ""
    out = []
    for line in src.splitlines()[1:]:
        if not line.startswith("#"):
            break
        out.append(line[2:] if line.startswith("# ") else line[1:])
    return "\n".join(out).strip()


def cited_lessons(src):
    seen = []
    src = re.sub(r"\n[ \t]*#+ ?", "\n", src)   # a citation wrapped across shell or Python comment lines
    for m in LESSON_CITE.finditer(" ".join(src.split())):
        if m.group(1) not in seen:
            seen.append(m.group(1))
    return seen


def ledger_events(path):
    """Event types this file writes: string constants given to a call named ...ledger(...) in Python, or the event word
    after `bin/ledger [-r RUN]` in a shell script."""
    src = open(path, errors="replace").read()
    found = []
    if is_python(path):
        try:
            tree = ast.parse(src)
        except SyntaxError:
            return []
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                f = node.func
                name = f.id if isinstance(f, ast.Name) else f.attr if isinstance(f, ast.Attribute) else ""
                if name == "ledger":
                    for a in node.args:
                        if isinstance(a, ast.Constant) and isinstance(a.value, str) and EVENT_NAME.match(a.value):
                            found.append(a.value)
    else:
        found = EVENT_SH.findall(src)
    return sorted(set(found))


def summary(doc):
    """One line for the index: the first sentence of the first paragraph that is not a usage line."""
    for para in re.split(r"\n\s*\n", doc):
        # A summary carries no lesson citation: cut short it would point at no lesson; the tool's page lists them.
        p = re.sub(r"\s*\(LESSONS\.md [^)]*\)|\s*LESSONS\.md [\"“][^\"”]*[\"”],?", "", " ".join(para.split()))
        if p and not p.startswith("bin/") and not p.startswith("Usage"):
            s = re.split(r"(?<=[.:;])\s", p, maxsplit=1)[0]
            return s[:200].replace("|", "\\|")
    return (" ".join(doc.split()[:20]) or "(no docstring)").replace("|", "\\|")


def tools(root):
    b = os.path.join(root, "bin")
    if not os.path.isdir(b):
        return []
    return sorted(n for n in os.listdir(b) if os.path.isfile(os.path.join(b, n)) and not n.endswith(".pyc"))


def deny_texts(hook_path):
    """(function, text) for every call of deny() or gate_deny() in the hook; a formatted part shows as `…`."""
    tree = ast.parse(open(hook_path).read())
    out = []

    def text(node):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            return node.value
        if isinstance(node, ast.JoinedStr):
            return "".join(v.value if isinstance(v, ast.Constant) else "…" for v in node.values)
        if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
            return text(node.left) + text(node.right)
        return "…"

    for fn in [n for n in tree.body if isinstance(n, ast.FunctionDef)]:
        for node in ast.walk(fn):
            if (isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id in ("deny", "gate_deny")
                    and node.args and fn.name not in ("deny", "gate_deny")):
                out.append((fn.name, " ".join(text(node.args[0]).split())))
    return out


def render(root):
    """{relative path: text} of every generated page."""
    pages = {}
    names = tools(root)
    events = {}
    rows, internal = [], []
    for n in names:
        path = os.path.join(root, "bin", n)
        doc = own_doc(path)
        src = open(path, errors="replace").read()
        lessons = cited_lessons(src)
        evs = ledger_events(path)
        for e in evs:
            events.setdefault(e, []).append(f"bin/{n}")
        kind = ("An internal module: imported by the tools, not run directly." if n.startswith("_")
                else "A tool: run it from the root of an instance (or of the kit, for the kit's own tools).")
        body = [GEN_MARK, "", f"# `bin/{n}`", "", kind, f"Source: [`bin/{n}`](../../../bin/{n})", "",
                "## What it says about itself", "", "```text", doc or "(no docstring)", "```", "",
                "## Lessons it cites", ""]
        body += [f"- → **{l}**" for l in lessons] or ["None."]
        body += ["", "## Ledger events it writes", ""]
        body += [f"- `{e}`" for e in evs] or ["None."]
        pages[f"docs/reference/tools/{n}.md"] = "\n".join(body) + "\n"
        (internal if n.startswith("_") else rows).append(f"| [`{n}`]({n}.md) | {summary(doc)} |")
    idx = [GEN_MARK, "", "# Tools", "",
           "Every program in `bin/`, each page generated from the program's own docstring. Every tool refuses what "
           "`RULES.md` says it refuses; the page quotes the tool, the rules are the authority.", "",
           "| tool | what it does |", "|---|---|"] + rows
    if internal:
        idx += ["", "## Internal modules", "", "| module | what it does |", "|---|---|"] + internal
    pages["docs/reference/tools/README.md"] = "\n".join(idx) + "\n"
    hook = os.path.join(root, HOOK)
    if os.path.isfile(hook):
        for e in ledger_events(hook):
            events.setdefault(e, []).append(HOOK)
        h = [GEN_MARK, "", "# What the hook refuses", "",
             f"Every refusal [`{HOOK}`](../../{HOOK}) can give, in its own words, grouped by the function that gives it. "
             "`gate_*` functions guard an orchestrator session; `main` guards a worker. A `…` stands for a value "
             "filled in when the refusal is given.", ""]
        cur = None
        for fn, t in deny_texts(hook):
            if fn != cur:
                h += ["", f"## `{fn}`", ""]
                cur = fn
            h.append(f"- {t}")
        pages["docs/reference/hook-refusals.md"] = "\n".join(h).replace("\n\n\n", "\n\n") + "\n"
    ev = [GEN_MARK, "", "# Ledger events", "",
          "Every event type a tool or the hook writes to `LEDGER.log` (the append-only log; agents write it and never read "
          "it), and who writes it.", "", "| event | written by |", "|---|---|"]
    for e in sorted(events):
        ev.append(f"| `{e}` | " + ", ".join(sorted(set(events[e]))) + " |")
    pages["docs/reference/ledger-events.md"] = "\n".join(ev) + "\n"
    return pages


def write_all(root):
    for rel, text in render(root).items():
        p = os.path.join(root, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, "w") as f:
            f.write(text)


if __name__ == "__main__":
    r = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    write_all(r)
    print(f"gen_reference: {len(render(r))} pages written under {os.path.join(r, 'docs', 'reference')}")
